area:web:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**'
area:api:
  - changed-files:
      - any-glob-to-any-file: 'apps/api/**'
ci:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**'
      - any-glob-to-any-file: 'infra/**'
e2e:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/tests/**'
security/csp:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/middleware.ts'
      - any-glob-to-any-file: 'apps/web/app/layout.tsx'
export:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/app/jobs/quote/page.tsx'
      - any-glob-to-any-file: 'apps/web/next.config.mjs'
docs:
  - changed-files:
      - any-glob-to-any-file: 'README.md'
      - any-glob-to-any-file: 'RELEASE_NOTES.md'
      - any-glob-to-any-file: 'apps/web/PR_SUMMARY.md'
