-- Generated by prisma migrate diff for Milestone M4 scheduling enhancements
-- Adds scheduling, reminder, and payout metadata to Assignment

-- CreateEnum
CREATE TYPE "ScheduleProposedBy" AS ENUM ('CUSTOMER', 'PROVIDER', 'SYSTEM');

-- CreateEnum
CREATE TYPE "AssignmentReminderStatus" AS ENUM ('NONE', 'QUEUED', 'SENT', 'OVERDUE');

-- CreateEnum
CREATE TYPE "AssignmentPayoutStatus" AS ENUM ('PENDING', 'AWAITING_APPROVAL', 'APPROVED', 'PAID', 'BLOCKED');

-- AlterTable
ALTER TABLE "Assignment" ADD COLUMN     "payoutApprovedAt" TIMESTAMP(3),
ADD COLUMN     "payoutApprovedBy" TEXT,
ADD COLUMN     "payoutStatus" "AssignmentPayoutStatus" NOT NULL DEFAULT 'PENDING',
ADD COLUMN     "rejectedAt" TIMESTAMP(3),
ADD COLUMN     "reminderCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "reminderLastSentAt" TIMESTAMP(3),
ADD COLUMN     "reminderStatus" "AssignmentReminderStatus" NOT NULL DEFAULT 'NONE',
ADD COLUMN     "scheduleNotes" TEXT,
ADD COLUMN     "scheduleProposedAt" TIMESTAMP(3),
ADD COLUMN     "scheduleProposedBy" "ScheduleProposedBy",
ADD COLUMN     "scheduleVersion" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "scheduledEnd" TIMESTAMP(3),
ADD COLUMN     "scheduledStart" TIMESTAMP(3),
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL,
ALTER COLUMN "status" SET DEFAULT 'pending_schedule';

-- CreateIndex
CREATE INDEX "Assignment_status_idx" ON "Assignment"("status");

-- CreateIndex
CREATE INDEX "Assignment_reminderStatus_idx" ON "Assignment"("reminderStatus");

-- CreateIndex
CREATE INDEX "Assignment_payoutStatus_idx" ON "Assignment"("payoutStatus");
